"""
Django settings for TutsDjango project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8!u7$)r42c$wsfvr6=@+xvafr9w@tzw2hqb_0x*l7qgqvpwz%n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['spoofed-domain.com', 'localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    # Contrib apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',  # Messages framework
    'django.contrib.staticfiles',

    # 3rd party
    'social_django',
    'rest_framework',

    # My apps
    'demos.apps.DemosConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',  # Messages framework
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TutsDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TutsDjango.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

from django.core.urlresolvers import reverse_lazy

# When the user successfully logs in, he will be redirected to LOGIN_REDIRECT_URL, so no need to ?next=/some-path
LOGIN_REDIRECT_URL = reverse_lazy('auth-status')
# When a View is only accessible by authenticated users and the user is not authenticated, contrib auth app will redirect
# The user to the below defined LOGIN_URL
LOGIN_URL = reverse_lazy('login')
# Default url to logout
LOGOUT_URL = reverse_lazy('logout')

# I am telling Django which backend to use to send emails, as you may guess, this backend will output the email
# on the console,
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# if you don't set EMAIL_BACKEND then the default is django.core.mail.backends.smtp.EmailBackend which is configured with the below

'''
EMAIL_HOST = 'localhost' # if empty default localhost
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_PORT = 25 # if empty default 25
EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = 'Admin <admin@no-reply.com>'
'''

AUTHENTICATION_BACKENDS = [
    'social_core.backends.open_id.OpenIdAuth',
    'social_core.backends.google.GoogleOpenId',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.google.GoogleOAuth',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.yahoo.YahooOpenId',
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.instagram.InstagramOAuth2',

    'django.contrib.auth.backends.ModelBackend',
    'demos.auth.CustomEmailAuthBackend.EmailAuthBackend',
]

SOCIAL_AUTH_FACEBOOK_KEY = '128293367887097'
SOCIAL_AUTH_FACEBOOK_SECRET = 'f72bd95736f5c445a363708d30f57717'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '230042110164-3iqqe19lfao63cktodtnir64mgd9inli.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'Z3Sf7MEvc8eKMkONL123q80_'
# SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = []

SOCIAL_AUTH_TWITTER_KEY = '6ncIwDq6PU8HvTxtKBCd00e2j'
SOCIAL_AUTH_TWITTER_SECRET = 'ykKUeOsZf6gNZVgZYDKBZBEz30cynkqOiI0sSpbiNQEhULbfDY'

SOCIAL_AUTH_GITHUB_KEY = '5ba258d10e1333892ee6'
SOCIAL_AUTH_GITHUB_SECRET = '3c9d5f520b676d0c37277c0399c00ed0ffd1c98c'
# https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-scopes-for-oauth-apps/
SOCIAL_AUTH_GITHUB_SCOPE = ['user:email']

SOCIAL_AUTH_INSTAGRAM_KEY = ''
SOCIAL_AUTH_INSTAGRAM_SECRET = ''
SOCIAL_AUTH_INSTAGRAM_AUTH_EXTRA_ARGUMENTS = {'scope': 'likes comments relationships'}

'''
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAdminUser',
    ],
    'PAGE_SIZE': 10
}
'''